### PR TITLE
Fine Tunes for the USB-C Version

### PR DESCRIPTION
**Pull request by SeDi343**
Fine Tunes for the USB-C Version and included @dev-soragoto his changes.

### CODE REVIEW

**Comment by SeDi343** [comment]
> Fails to compile
> 
> ```
> [253ms][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git remote add patch https://github.com/SeDi343/Linux-Magic-Trackpad-2-USB-C-Driver.git
> [0.256s][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git pull patch
> remote: Enumerating objects: 42, done.
> remote: Counting objects: 100% (42/42), done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 42 (delta 18), reused 36 (delta 15), pack-reused 0 (from 0)
> Unpacking objects: 100% (42/42), 14.03 KiB | 897.00 KiB/s, done.
> From https://github.com/SeDi343/Linux-Magic-Trackpad-2-USB-C-Driver
>  * [new branch]      main       -> patch/main
> You asked to pull from the remote 'patch', but did not specify
> a branch. Because this is not the default configured remote
> for your current branch, you must specify a branch on the command line.
> [407ms][1][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git checkout patch/main
> Note: switching to 'patch/main'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at 1d79877 253 is max pressure
> [9ms][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ chmod u+x install.sh
> [7ms][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ sudo ./install.sh
> +++ dirname ./install.sh
> ++ cd .
> ++ pwd
> + DIR=/home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver
> + chmod u+x /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
> + /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
> + dkms_name=hid-magicmouse-dkms
> + dkms_version=6.11+magicmouse2
> +++ dirname /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
> ++ cd /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts
> ++ pwd
> + DIR=/home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts
> + dkms status -m hid-magicmouse-dkms -v 6.11+magicmouse2
> + egrep '(added|built|installed)'
> egrep: warning: egrep is obsolescent; using grep -E
> + dkms status -m hid-magicmouse-dkms -v 6.11+magicmouse2
> + egrep '(built|installed)'
> egrep: warning: egrep is obsolescent; using grep -E
> + dkms build hid-magicmouse-dkms/6.11+magicmouse2
> 
> Sign command: /usr/lib/modules/6.12.3-arch1-1/build/scripts/sign-file
> Signing key: /var/lib/dkms/mok.key
> Public certificate (MOK): /var/lib/dkms/mok.pub
> Deprecated feature: REMAKE_INITRD (/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/source/dkms.conf)
> 
> Cleaning build area... done.
> Building module(s)...(bad exit status: 2)
> Failed command:
> make -j32 KERNELRELEASE=6.12.3-arch1-1 KERNEL_VERSION=6.12.3-arch1-1 all
> 
> Error! Bad return status for module build on kernel: 6.12.3-arch1-1 (x86_64)
> Consult /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/make.log for more information.
> [3.244s][10][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ cat /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/make.log
> DKMS make.log for hid-magicmouse-dkms/6.11+magicmouse2 for kernel 6.12.3-arch1-1 (x86_64)
> Mon Dec  9 06:50:56 AM MST 2024
> make -C /lib/modules/6.12.3-arch1-1/build M=/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build modules
> make[1]: Entering directory '/usr/lib/modules/6.12.3-arch1-1/build'
>   CC [M]  /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.o
> /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.c:989:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
>   989 |         .report_fixup = magicmouse_report_fixup,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.c:989:25: note: (near initialization for ‘magicmouse_driver.report_fixup’)
> make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.o] Error 1
> make[2]: *** [/usr/lib/modules/6.12.3-arch1-1/build/Makefile:1936: /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build] Error 2
> make[1]: *** [Makefile:224: __sub-make] Error 2
> make[1]: Leaving directory '/usr/lib/modules/6.12.3-arch1-1/build'
> make: *** [Makefile:9: all] Error 2
> ```

Mistaken by User. Commented in https://github.com/mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver/issues/4

**Review by mr-cal — COMMENTED** [review]
Hi, sorry about the late review - I made these comments a few days ago and forgot to submit the review.

File: linux/drivers/hid/hid-magicmouse.c [hunk 1]
```diff
@@ -928,8 +933,13 @@ static void magicmouse_remove(struct hid_device *hdev)
 	hid_hw_stop(hdev);
 }
 
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6, 12, 0)
```
[the remark this answers is not in the document]
Comment (dev-soragoto) [reply linux/drivers/hid/hid-magicmouse.c:943]: > This function isn't used outside of this file so I can't figure out why this compatibility is needed. I wonder if this is related to the error that @jslay88 is seeing?

https://lore.kernel.org/all/20240803-hid-const-fixup-v2-6-f53d7a7b29d8@weissschuh.net/

Because of this change, the kernel version needs to be checked during compilation.

[the remark this answers is not in the document]
Comment (mr-cal) [reply linux/drivers/hid/hid-magicmouse.c:943]: I see, thanks.

File: linux/drivers/hid/hid-magicmouse.c [hunk 2]
```diff
@@ -566,10 +568,13 @@ static int magicmouse_setup_input(struct input_dev *input, struct hid_device *hd
 		 * loaded, whether connected through bluetooth or USB.
 		 */
 		if (hdev->vendor == BT_VENDOR_ID_APPLE) {
-			if (input->id.version == TRACKPAD2_2021_BT_VERSION)
+			if (input->id.version == TRACKPAD2_2021_BT_VERSION) {
+				input->name = "Apple Inc. Magic Trackpad 2021";
+			} else if (input->id.version == TRACKPAD_2024_BT_VERSION) {
+				input->name = "Apple Inc. Magic Trackpad USB-C";
```
[the remark this answers is not in the document]
Comment (dev-soragoto) [reply linux/drivers/hid/hid-magicmouse.c:574]: If I remember correctly ,the name reported by the trackpad usn-c over USB is "Apple Inc. Magic Trackpad." , I'm not sure if the device name reported via Bluetooth needs to reflect the current hardware version. However, I tried to submit a patch.
https://patchwork.kernel.org/project/linux-input/patch/20241202060545.21193-1-soragoto@soragoto.io/

[the remark this answers is not in the document]
Comment (SeDi343) [reply linux/drivers/hid/hid-magicmouse.c:574]: @mr-cal and @dev-soragoto should the name be "Apple Inc. Magic Trackpad"? And rename the vars to `TRACKPAD2_BT_VERSION` and `TRACKPAD2_USBC_BT_VERSION`?

[the remark this answers is not in the document]
Comment (jslay88) [reply linux/drivers/hid/hid-magicmouse.c:574]: For mine libinput shows for Bluetooth

```
Device:           Apple Inc. Magic Trackpad USB-C
Kernel:           /dev/input/event30
Group:            10
Seat:             seat0, default
Size:             162x115mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    enabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    button-areas *clickfinger
Disable-w-typing: n/a
Disable-w-trackpointing: n/a
Accel profiles:   flat *adaptive custom
Rotation:         n/a
```

For USB-C it shows

```
Device:           Apple Inc. Magic Trackpad
Kernel:           /dev/input/event23
Group:            7
Seat:             seat0, default
Size:             162x115mm
Capabilities:     pointer gesture
Tap-to-click:     disabled
Tap-and-drag:     enabled
Tap drag lock:    disabled
Left-handed:      disabled
Nat.scrolling:    enabled
Middle emulation: disabled
Calibration:      n/a
Scroll methods:   *two-finger edge
Click methods:    button-areas *clickfinger
Disable-w-typing: enabled
Disable-w-trackpointing: enabled
Accel profiles:   flat *adaptive custom
Rotation:         n/a
```

[the remark this answers is not in the document]
Comment (mr-cal) [reply linux/drivers/hid/hid-magicmouse.c:574]: Here's my context, I could be misunderstanding the commit history: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/hid/hid-magicmouse.c?h=v6.13-rc2&id=5768701edcb7d7ff8abaa085996a5c1cb30d765e

[the remark this answers is not in the document]
Comment (dev-soragoto) [reply linux/drivers/hid/hid-magicmouse.c:574]: > Here's my context, I could be misunderstanding the commit history: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/hid/hid-magicmouse.c?h=v6.13-rc2&id=5768701edcb7d7ff8abaa085996a5c1cb30d765e

I understand your point. To keep the device name consistent with the USB connection, could we make the changes this way

```c
if (hdev->vendor == BT_VENDOR_ID_APPLE) {
	switch (input->id.version) {
		case TRACKPAD2_2021_BT_VERSION:
		case TRACKPAD_2024_BT_VERSION;
			input->name = "Apple Inc. Magic Trackpad";
			break;
		default:
			input->name = "Apple Inc. Magic Trackpad2";
			break;
	}
} else { /* USB_VENDOR_ID_APPLE */
	input->name = hdev->name;
}
```

However, there is still a question, why is the default device name's suffix 2, Before 2021, were the device names reported via USB all like this?

[the remark this answers is not in the document]
Comment (dev-soragoto) [reply linux/drivers/hid/hid-magicmouse.c:574]: > Here's my context, I could be misunderstanding the commit history: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/drivers/hid/hid-magicmouse.c?h=v6.13-rc2&id=5768701edcb7d7ff8abaa085996a5c1cb30d765e

I understand your point. To keep the device name consistent with the USB connection, could we make the changes this way

```c
if (hdev->vendor == BT_VENDOR_ID_APPLE) {
	switch (input->id.version) {
		case TRACKPAD2_2021_BT_VERSION:
		case TRACKPAD_2024_BT_VERSION;
			input->name = "Apple Inc. Magic Trackpad";
			break;
		default:
			input->name = "Apple Inc. Magic Trackpad2";
			break;
	}
} else { /* USB_VENDOR_ID_APPLE */
	input->name = hdev->name;
}
```

However, there is still a question, why is the default device name's suffix 2, Before 2021, were the device names reported via USB all like this?

[the remark this answers is not in the document]
Comment (SeDi343) [reply linux/drivers/hid/hid-magicmouse.c]: Is https://github.com/mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver/blob/2a495f025d7ea838a3396b3e556e3f5d2d1160c6/linux/drivers/hid/hid-magicmouse.c#L567-L576 how you would prefer it?

I am quite confused by the suffix of 2. My Lightning has suffix 2. My USBC does not.

[the remark this answers is not in the document]
Comment (SeDi343) [reply linux/drivers/hid/hid-magicmouse.c]: When the lightning version is now connected via usb its without the suffix.

[the remark this answers is not in the document]
Comment (dev-soragoto) [reply linux/drivers/hid/hid-magicmouse.c]: > Is
> 
> https://github.com/mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver/blob/2a495f025d7ea838a3396b3e556e3f5d2d1160c6/linux/drivers/hid/hid-magicmouse.c#L567-L576
> 
> how you would prefer it?
> I am quite confused by the suffix of 2. My Lightning has suffix 2. My USBC does not.

I suspect that only a few versions of the hardware will have the suffix 2,  but now the default device name's suffix 2, I don't know if doing this is correct.

**Comment by SeDi343** [comment]
Added https://github.com/mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver/pull/3/commits/df045061866ddf430c26312dfaf198ef788de14e maybe you can check it out and read out something @mr-cal. Have have to say, I do not see a difference really :-1:

File: linux/drivers/hid/hid-magicmouse.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (mr-cal) [reply linux/drivers/hid/hid-magicmouse.c]: Since it seems like only the 2021 trackpad reports the name with a "2" when connected via USB, then it is the only model that needs special handling.  Maybe we should to just leave this section as-is?

[the remark this answers is not in the document]
Comment (SeDi343) [reply linux/drivers/hid/hid-magicmouse.c]: > Since it seems like only the 2021 trackpad reports the name with a "2" when connected via USB, then it is the only model that needs special handling. Maybe we should to just leave this section as-is?

Do you mean it this way?

```
 if (hdev->vendor == BT_VENDOR_ID_APPLE) { 
 	if (input->id.version == TRACKPAD2_2021_BT_VERSION) { 
 		input->name = "Apple Inc. Magic Trackpad 2"; 
 	} else { 
 		input->name = "Apple Inc. Magic Trackpad"; 
 	} 
 } else { /* USB_VENDOR_ID_APPLE */ 
 	input->name = hdev->name; 
 } 
```

[the remark this answers is not in the document]
Comment (dev-soragoto) [reply linux/drivers/hid/hid-magicmouse.c]: > Since it seems like only the 2021 trackpad reports the name with a "2" when connected via USB, then it is the only model that needs special handling. Maybe we should to just leave this section as-is?

https://github.com/mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver/blob/7bf74255ea0dd6a9c0c7790cf4c115b52637e976/linux/drivers/hid/hid-magicmouse.c#L568-L572

From this piece of code, it seems that the 2021 version's name probably doesn't include "2" either. At the same time, the 2024 version still doesn’t include "2" either.

[the remark this answers is not in the document]
Comment (SeDi343) [reply linux/drivers/hid/hid-magicmouse.c]: @mr-cal my Ligthning Version has PPN A1535 and has 613 (0x265) which is not `#define TRACKPAD2_2021_BT_VERSION 0x110`

[the remark this answers is not in the document]
Comment (SeDi343) [reply linux/drivers/hid/hid-magicmouse.c]: @mr-cal @dev-soragoto do you know how you find out the Version Number of `TRACKPAD2_2021_BT_VERSION 0x110` and `TRACKPAD_USBC_BT_VERSION 0x314` via Bluetooth. I can not help myself finding this out for my bluetooth Trackpad. I want to make sure, my Lightning Trackpad indeed has the 0x110 Version, since it shows `input->name = "Apple Inc. Magic Trackpad 2";` when connected via Bluetooth.

File: linux/drivers/hid/hid-magicmouse.c [hunk 3]
```diff
@@ -400,10 +449,43 @@ static int magicmouse_raw_event(struct hid_device *hdev,
...
+		clicks = data[1];
+
+#if DEBUG
+		u8 *tdata = 0;
+#endif
+		for (ii = 0; ii < npoints; ii++) {
 			magicmouse_emit_touch(msc, ii, data + ii * 9 + 4);
+#if DEBUG
+			tdata = data + ii * 9 + 4;
+			hid_notice(hdev, "| ID: %02d | TS %06d | X: %05d Y: %05d | Size: %03d | Orientation: %02d | T Major %03d T Minor %03d | Pressure %03d | State %03d | Down %d | Unkown %02d & %d |\n",
```
Comment (mr-cal) [inline linux/drivers/hid/hid-magicmouse.c:461]:
```suggestion
			hid_notice(hdev, "| ID: %02d | TS %06d | X: %05d Y: %05d | Size: %03d | Orientation: %02d | T Major %03d T Minor %03d | Pressure %03d | State %03d | Down %d | Unknown %02d & %d |\n",
```

File: linux/drivers/hid/hid-magicmouse.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (mr-cal) [reply linux/drivers/hid/hid-magicmouse.c]: I've been finding it with:
```
sudo dmesg | grep "magic"
[ 5951.519896] magicmouse 0005:004C:0324.0003: input,hidraw2: BLUETOOTH HID v3.14 Mouse [Callahan’s Magic Trackpad] on 0c:54:15:d5:31:93
```

Mine is reporting a custom name after I connected it to a macbook for comparison, but I believe the `v3.14` in that string is represented by `0x314`.

**Review by mr-cal — COMMENTED** [review]
I've been playing with this for a few hours and your debugging lines and comments are quite helpful.  Unfortunately I am no closer to decoding those unknown values in the data layout.

I'm happy to land this as-is if you are ready.  If we figure out anything more, we can do a second PR with improvements.  What do you think?

**Comment by SeDi343** [comment]
> I've been playing with this for a few hours and your debugging lines and comments are quite helpful. Unfortunately I am no closer to decoding those unknown values in the data layout.
> 
> I'm happy to land this as-is if you are ready. If we figure out anything more, we can do a second PR with improvements. What do you think?

Alright, I want to play a bit with the name, now with the new information regarding dmsg. And will make a PR out of the Draft.

File: linux/drivers/hid/hid-magicmouse.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (SeDi343) [reply linux/drivers/hid/hid-magicmouse.c]: Alright, this was my output of `sudo dmesg | grep "magic"`:
```
> sudo dmesg | grep "magic"
[sudo] password for admin: 
[  597.114036] hid_magicmouse: loading out-of-tree module taints kernel.
[  597.224027] magicmouse 0005:004C:0265.0008: unknown main item tag 0x0
[  597.224621] magicmouse 0005:004C:0265.0008: input,hidraw3: BLUETOOTH HID v3.11 Mouse [Magic Trackpad von Sebastian] on 7c:21:4a:24:2f:24
```
Added now `#define TRACKPAD2_A1535_2733_VERSION 0x311` to the list of item that do not have a 2 in the suffix.  See https://github.com/mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver/pull/3/commits/8d294fc0f8b77f6eb95c87fb33252a114377e06f

**Review by mr-cal — APPROVED** [review]
Looks good to me, thanks!

I'm surprised there is another variant v3.11.

**Comment by SeDi343** [comment]
> Looks good to me, thanks!
> 
> I'm surprised there is another variant, v3.11.

Thanks for the help!

I was too. I have not yet considered submitting those changes to the kernel. You can submit these changes if you want :)
