### ISSUE TITLE
6.12 issues

### ISSUE THREAD

**Issue by jslay88** [mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver#4]
I just received my new trackpad today, and am noticing the "no driver' behavior of "point, hard click". From my understanding, this upstreamed fix should have been in 6.12, no? Do I need to try and update the firmware on the trackpad first?

```
Linux 6.12.3-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 06 Dec 2024 11:15:43 +0000 x86_64 GNU/Linux
```

MacBook Pro is showing it has firmware 3.1.4

**Comment by SeDi343** [comment]
Hey @jslay88 check out my PR. https://github.com/mr-cal/Linux-Magic-Trackpad-2-USB-C-Driver/pull/3. Thanks to @dev-soragoto his input it should work with upstream kernel updates when PR is merged and also updated to Linux repository.

**Comment by jslay88** [comment]
Fails to compile

```
[253ms][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git remote add patch https://github.com/SeDi343/Linux-Magic-Trackpad-2-USB-C-Driver.git
[0.256s][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git pull patch
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 42 (delta 18), reused 36 (delta 15), pack-reused 0 (from 0)
Unpacking objects: 100% (42/42), 14.03 KiB | 897.00 KiB/s, done.
From https://github.com/SeDi343/Linux-Magic-Trackpad-2-USB-C-Driver
 * [new branch]      main       -> patch/main
You asked to pull from the remote 'patch', but did not specify
a branch. Because this is not the default configured remote
for your current branch, you must specify a branch on the command line.
[407ms][1][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git checkout patch/main
Note: switching to 'patch/main'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 1d79877 253 is max pressure
[9ms][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ chmod u+x install.sh
[7ms][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ sudo ./install.sh
+++ dirname ./install.sh
++ cd .
++ pwd
+ DIR=/home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver
+ chmod u+x /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
+ /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
+ dkms_name=hid-magicmouse-dkms
+ dkms_version=6.11+magicmouse2
+++ dirname /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
++ cd /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts
++ pwd
+ DIR=/home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts
+ dkms status -m hid-magicmouse-dkms -v 6.11+magicmouse2
+ egrep '(added|built|installed)'
egrep: warning: egrep is obsolescent; using grep -E
+ dkms status -m hid-magicmouse-dkms -v 6.11+magicmouse2
+ egrep '(built|installed)'
egrep: warning: egrep is obsolescent; using grep -E
+ dkms build hid-magicmouse-dkms/6.11+magicmouse2

Sign command: /usr/lib/modules/6.12.3-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Deprecated feature: REMAKE_INITRD (/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/source/dkms.conf)

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
make -j32 KERNELRELEASE=6.12.3-arch1-1 KERNEL_VERSION=6.12.3-arch1-1 all

Error! Bad return status for module build on kernel: 6.12.3-arch1-1 (x86_64)
Consult /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/make.log for more information.
[3.244s][10][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ cat /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/make.log
DKMS make.log for hid-magicmouse-dkms/6.11+magicmouse2 for kernel 6.12.3-arch1-1 (x86_64)
Mon Dec  9 06:50:56 AM MST 2024
make -C /lib/modules/6.12.3-arch1-1/build M=/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build modules
make[1]: Entering directory '/usr/lib/modules/6.12.3-arch1-1/build'
  CC [M]  /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.o
/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.c:989:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
  989 |         .report_fixup = magicmouse_report_fixup,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.c:989:25: note: (near initialization for ‘magicmouse_driver.report_fixup’)
make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.o] Error 1
make[2]: *** [/usr/lib/modules/6.12.3-arch1-1/build/Makefile:1936: /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.12.3-arch1-1/build'
make: *** [Makefile:9: all] Error 2
```

**Comment by dev-soragoto** [comment]
> Fails to compile
> 
> ```
> [253ms][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git remote add patch https://github.com/SeDi343/Linux-Magic-Trackpad-2-USB-C-Driver.git
> [0.256s][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git pull patch
> remote: Enumerating objects: 42, done.
> remote: Counting objects: 100% (42/42), done.
> remote: Compressing objects: 100% (13/13), done.
> remote: Total 42 (delta 18), reused 36 (delta 15), pack-reused 0 (from 0)
> Unpacking objects: 100% (42/42), 14.03 KiB | 897.00 KiB/s, done.
> From https://github.com/SeDi343/Linux-Magic-Trackpad-2-USB-C-Driver
>  * [new branch]      main       -> patch/main
> You asked to pull from the remote 'patch', but did not specify
> a branch. Because this is not the default configured remote
> for your current branch, you must specify a branch on the command line.
> [407ms][1][main][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ git checkout patch/main
> Note: switching to 'patch/main'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at 1d79877 253 is max pressure
> [9ms][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ chmod u+x install.sh
> [7ms][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ sudo ./install.sh
> +++ dirname ./install.sh
> ++ cd .
> ++ pwd
> + DIR=/home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver
> + chmod u+x /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
> + /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
> + dkms_name=hid-magicmouse-dkms
> + dkms_version=6.11+magicmouse2
> +++ dirname /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts/install.sh
> ++ cd /home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts
> ++ pwd
> + DIR=/home/jslay/Linux-Magic-Trackpad-2-USB-C-Driver/scripts
> + dkms status -m hid-magicmouse-dkms -v 6.11+magicmouse2
> + egrep '(added|built|installed)'
> egrep: warning: egrep is obsolescent; using grep -E
> + dkms status -m hid-magicmouse-dkms -v 6.11+magicmouse2
> + egrep '(built|installed)'
> egrep: warning: egrep is obsolescent; using grep -E
> + dkms build hid-magicmouse-dkms/6.11+magicmouse2
> 
> Sign command: /usr/lib/modules/6.12.3-arch1-1/build/scripts/sign-file
> Signing key: /var/lib/dkms/mok.key
> Public certificate (MOK): /var/lib/dkms/mok.pub
> Deprecated feature: REMAKE_INITRD (/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/source/dkms.conf)
> 
> Cleaning build area... done.
> Building module(s)...(bad exit status: 2)
> Failed command:
> make -j32 KERNELRELEASE=6.12.3-arch1-1 KERNEL_VERSION=6.12.3-arch1-1 all
> 
> Error! Bad return status for module build on kernel: 6.12.3-arch1-1 (x86_64)
> Consult /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/make.log for more information.
> [3.244s][10][1d79877][~/Linux-Magic-Trackpad-2-USB-C-Driver]$ cat /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/make.log
> DKMS make.log for hid-magicmouse-dkms/6.11+magicmouse2 for kernel 6.12.3-arch1-1 (x86_64)
> Mon Dec  9 06:50:56 AM MST 2024
> make -C /lib/modules/6.12.3-arch1-1/build M=/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build modules
> make[1]: Entering directory '/usr/lib/modules/6.12.3-arch1-1/build'
>   CC [M]  /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.o
> /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.c:989:25: error: initialization of ‘const __u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘const unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} from incompatible pointer type ‘__u8 * (*)(struct hid_device *, __u8 *, unsigned int *)’ {aka ‘unsigned char * (*)(struct hid_device *, unsigned char *, unsigned int *)’} [-Wincompatible-pointer-types]
>   989 |         .report_fixup = magicmouse_report_fixup,
>       |                         ^~~~~~~~~~~~~~~~~~~~~~~
> /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.c:989:25: note: (near initialization for ‘magicmouse_driver.report_fixup’)
> make[3]: *** [scripts/Makefile.build:229: /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build/hid-magicmouse.o] Error 1
> make[2]: *** [/usr/lib/modules/6.12.3-arch1-1/build/Makefile:1936: /var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/build] Error 2
> make[1]: *** [Makefile:224: __sub-make] Error 2
> make[1]: Leaving directory '/usr/lib/modules/6.12.3-arch1-1/build'
> make: *** [Makefile:9: all] Error 2
> ```

Perhaps you need to uninstall driver or
delete `/var/lib/dkms/hid-magicmouse-dkms/6.11+magicmouse2/` first and try it again

**Comment by jslay88** [comment]
Ahh yeah, good call. Seems to be working great now. However, when it connects with bluetooth, it initially reports a low battery notification ~3-5%, then shows the correct battery level.

**Comment by dev-soragoto** [comment]
> Ahh yeah, good call. Seems to be working great now. However, when it connects with bluetooth, it initially reports a low battery notification ~3-5%, then shows the correct battery level.


I also noticed this, but I don't know how to fix it. Fortunately, it doesn't affect usage:(

**Comment by jslay88** [comment]
> > Ahh yeah, good call. Seems to be working great now. However, when it connects with bluetooth, it initially reports a low battery notification ~3-5%, then shows the correct battery level.
> 
> I also noticed this, but I don't know how to fix it. Fortunately, it doesn't affect usage:(

At least its a consistent behavior and not unique. Somewhere to start at least.

**Comment by SeDi343** [comment]
> Ahh yeah, good call. Seems to be working great now. However, when it connects with bluetooth, it initially reports a low battery notification ~3-5%, then shows the correct battery level.

Could this be regarding to `#define USB_BATTERY_TIMEOUT_MS 60000`?
